### ISSUE TITLE
About reproduce your code

### ISSUE THREAD

**Issue by lzh1-hub** [cikrhazo/Invertible-Image-Decolorization#2]

**Comment by cikrhazo** [comment]
Could you please provide some more details? So I could help to see where the problem is.

**Comment by lzh1-hub** [comment]
I follow the parameter settings in the paper, c_weight=0.7, s_wight=0.5, r_wight=0.1, g_weight=1, the data set is also trained with VOC 8000 images, but the PSNR of the decolorized result is only about 25，the color psnr of the reverse process also only 20 db

**Comment by cikrhazo** [comment]
Have you tried to warm up the network? I've provided the log of my training in "./log".

**Comment by lzh1-hub** [comment]
Yes, I read your ./log/warmup.log, so I am very strange, I just changed the path of the dataset, no other changes in the code
